id = "xml"
name = "XML"
description = "XML syntax support."
version = "0.0.3"
schema_version = 1
authors = ["sweetppro"]
repository = "https://github.com/sweetppro/zed-xml"

[grammars.xml]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-xml"
commit = "96beba9f3e4156aaae64bb86997503b1ceb1283d"
path = "xml"
