id = "xml"
name = "XML"
description = "XML syntax support."
version = "0.1.0"
schema_version = 1
authors = ["sweetppro", "notpeter"]
repository = "https://github.com/sweetppro/zed-xml"

[grammars.xml]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-xml"
commit = "863dbc381f44f6c136a399e684383b977bb2beaa"
path = "xml"

# Upstream: https://github.com/eclipse-lemminx/lemminx
# Binaries: https://github.com/redhat-developer/vscode-xml
[language_servers.lemminx]
name = "lemminx"
language = "XML"
language_ids = { XML = "xml" }
