name = "XML"
grammar = "xml"
path_suffixes = [
    "xml",
    "xsd",
    "ascx",
    "atom",
    "axml",
    "axaml",
    "bpmn",
    "cpt",
    "csl",
    "csproj",
    "csproj.user",
    "dita",
    "ditamap",
    "dtd",
    "ent",
    "mod",
    "dtml",
    "entitlements",
    "fsproj",
    "fxml",
    "iml",
    "isml",
    "jmx",
    "launch",
    "menu",
    "mxml",
    "nuspec",
    "opml",
    "owl",
    "plist",
    "proj",
    "props",
    "pt",
    "publishsettings",
    "pubxml",
    "pubxml.user",
    "rbxlx",
    "rbxmx",
    "rdf",
    "rng",
    "rss",
    "shproj",
    "storyboard",
    "svg",
    "targets",
    "tld",
    "tmTheme",
    "tmx",
    "vbproj",
    "vbproj.user",
    "vcxproj",
    "vcxproj.filters",
    "wsdl",
    "wxi",
    "wxl",
    "wxs",
    "xaml",
    "xbl",
    "xcsettings",
    "xcprivacy",
    "xcscheme",
    "xcworkspacedata",
    "xib",
    "xlf",
    "xliff",
    "xpdl",
    "xul",
    "xoml",
    "xsl",
    "xslt",
]
block_comment = ["<!-- ", " -->"]
brackets = [{ start = "<", end = ">", close = true, newline = true }]
prettier_parser_name = "xml"
prettier_plugins = ["prettier-plugin-xml"]
